version: "3.9"

networks:
  aps:
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  postgres:
    image: postgres:13.3
    networks:
      aps:
        ipv4_address: 172.22.0.5
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=172.22.0.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "transaction"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  server:
    depends_on:
      - postgres
    networks:
      aps:
        ipv4_address: 172.22.0.6
    build: ./
    ports:
      - "5000:5000"
    environment:
      HOST_DB: 172.22.0.5


